### PR TITLE
Add F2FS support

### PR DESCRIPTION
**Pull request by ZVNexus**

### CODE REVIEW

**Comment by MatMoul** [comment]
I'm OK to add f2fs but not as first option...
Add it after xfs, f2fs is not a default format for a filesystem...

**Comment by TheLinuxNinja** [comment]
Grub support for F2FS will not be available until version 2.03
You will need a separate /boot that is not F2FS
You will NOT be able to generate /etc/fstab using UUID as Grub will not be able to find the UUID of the F2FS formatted partition.

This should not be merged until tested further, IMHO.

**Comment by MatMoul** [comment]
@TheLinuxNinja Thanks for the info, at this time, I not tested the f2fs and stoped the review on the order of the menu.
Waiting news

**Comment by ZVNexus** [comment]
@TheLinuxNinja Which is why I didn't add F2FS as a format option for /boot, do you mean it can't boot off F2FS disks? I have never have that problem when I used GRUB.

**Comment by MatMoul** [comment]
@ZVNexus Thanks for your PR...
Using f2fs as root work well...

**Pull request merged**
