### PR TITLE
wrap all bash variables in braces

### PR DESCRIPTION
**Pull request by TheLinuxNinja**
All bash variable expansion recommended to be ${var} instead of $var for clarity.

### CODE REVIEW

**Comment by MatMoul** [comment]
Hi and thanks for the hard work on the variables...
I've releved some error on lines using awk/gawk (line 237, 279, 317, 1022)

But for the whiptail variable, I'm not sure it's a good idea...
Whiptail and Dialog are not compatible...
Do you have tested the script with dialog? For me nothing work...

**Comment by TheLinuxNinja** [comment]
I found the awk issue before reading this. I'm testing fixes locally, now.
whiptail is a lesser version of dialog. I'm proactively adding the ability to swap out the executable for dialog or any other drop-in compatible binary. There are a few listed as compatible when I do review of whiptail usage examples online. Debian uses dialog.

I don't like hard-coding things where possible. I'm finding several opportunities for improvement, but will execute each of the set of fixes in separate branches and PR them individually.

We had an Arch Linux install party last weekend and used archfi. There were several issues. I'm hoping to address each of them and send you PRs for them so the next install party goes smoothly.

**Comment by TheLinuxNinja** [comment]
awk issue fixed and tested

**Comment by MatMoul** [comment]
Thanks for the awk issue...

I comming back for the dialogexe varname that has no sense (why dialog for whiptail and why exe?)
Secondly try to replace wipthail by dialog break the script...
It's more easy to use the whiptail command than a custom var name.

**Comment by TheLinuxNinja** [comment]
I found why the dialog replacement for whiptail wasn't working. I'll fix the issue in a future PR.
Updated commit to do JUST the brace additions to the bash vars.

**Comment by TheLinuxNinja** [comment]
squashed commits, removed old edits and force-pushed
this should be clean

**Pull request merged**
