### PR TITLE
Improve readme

### LINKED ISSUE #45: Add instructions to add the installer in the archiso.
There is [a guide on the Arch wiki](https://wiki.archlinux.org/index.php/Remastering_the_Install_ISO) to remaster the Arch iso.

In this way it's possible to add the arch installer in the iso before mounting the iso on a flash drive.

These instructions, or a link to this page could be added on the readme, which would look like this:

- archfi
    - How to use
        - Method a: create regular iso then download the script from it
        - Method b: create remastered including the script

Having the installation script already in the archiso could be really useful. Among other things, this would allow adding in that installer some functions that configure the internet connection.[1]

It would be very helpful in particular when installing Arch via a wireless connection (some modern laptop does not have Ethernet plug).

---

[1]: Note that I can help for this and suggest a PR.

### PR DESCRIPTION
**Pull request by roipoussiere**
- add instructions about internet connection (fix #45)
- improve readability without a markdown viewer (ie. avoid `<br/>`, etc.)

### CODE REVIEW

**Comment by TheLinuxNinja** [comment]
While in theory it's nice to have a README that doesn't require a markdown viewer, README.md is in fact a markdown file, is displayed by default by repo viewers, and is pretty much a standard for all git repos. I do agree, though, that being able to view it from the terminal and non-markdown capable editors is a huge bonus, while also using just enough markdown to properly format it for the markdown-enabled viewers. I support this change! Thanks!

**Comment by MatMoul** [comment]
@roipoussiere I just wanted to make sure you saw my code review on line 19-29...
@TheLinuxNinja I support this change too but as you say, need some changes on lines 19-29 to be more readable...

**Comment by roipoussiere** [comment]
> I just wanted to make sure you saw my code review on line 19-29...

Hmm, where is it?

**Comment by MatMoul** [comment]
@roipoussiere Just login and go on this page : https://github.com/MatMoul/archfi/pull/49/files
you need to sea my comment :
Line 19-29, looking result at https://github.com/roipoussiere/archfi/blob/patch-2/README.md
If SourceForge is down, use this instead: has an identation problem
For this part, I find more legible the current version which is more condanced

**Comment by roipoussiere** [comment]
> you need to sea my comment

It's strange because I don't see this comment, just my modifications.

**Comment by MatMoul** [comment]
No problem, the comment is :
Line 19-29, looking result at https://github.com/roipoussiere/archfi/blob/patch-2/README.md
If SourceForge is down, use this instead: has an identation problem
For this part, I find more legible the current version which is more condanced

**Comment by roipoussiere** [comment]
Ok, you mean using the syntax:

```
    some code
```

instead of

    ```
    some code
    ```

?

**Comment by roipoussiere** [comment]
Done :)

**Comment by MatMoul** [comment]
good first update but looking at https://github.com/roipoussiere/archfi/blob/patch-2/README.md
It's not possible as is... it's not correctly formatted...

**Comment by roipoussiere** [comment]
Ok it was because the Github markdown viewer doesn't like code sample inside lists (and now I remember that it was for this reason that I chose the ` ``` ` syntax at first).

I removed the list, then.

**Comment by MatMoul** [comment]
@roipoussiere I handle this PR but,
For a next PR it's better if you work on src branch, with this I can merge it with the Github webgui ;-)

**Comment by roipoussiere** [comment]
> For a next PR it's better if you work on src branch, with this I can merge it with the Github webgui ;-)

got it, sorry :D

**Comment by MatMoul** [comment]
@roipoussiere No problem, I'v added now a CONTRIBUTING.md that was missing on your first PR
see you

**Pull request merged**
