### PR TITLE
Update archfi

### PR DESCRIPTION
**Pull request by arnon001**

### CODE REVIEW

**Comment by MatMoul** [comment]
No description ?

I don't understand why you want to use x86 for old boot or mixed boot?

A little explanation would be nice!

**Comment by arnon001** [comment]
I Don't remember why i did that, but its supposed to be a x64 download and not a i386

**Comment by stevleibelt** [comment]
@arnon001 if you don't know, could you please close this ticket?

**Comment by MatMoul** [comment]
Thanks for reply, I close this PR for now

**Pull request closed without merging**
