### PR TITLE
Update Turkish

### PR DESCRIPTION
**Pull request by TeknoMobil**
Hello, translations with meaning disorder and all translation updated.

### CODE REVIEW

**Comment by MatMoul** [comment]
Thanks for your PR.
For the next time, try to read https://github.com/MatMoul/archfi/blob/master/CONTRIBUTING.md

**Comment by TeknoMobil** [comment]
Okey thanks

**Comment by MatMoul** [comment]
@TeknoMobil I coming back to you for this PR,
I've just see that you removed the font and now when I use Turkish in a VM, some chars aren't correctly displayed...
Can you confirm or take position ?

**Comment by TeknoMobil** [comment]
Sorry font has been added again.

**Pull request merged**
