### PR TITLE
Edit archfi script

### PR DESCRIPTION
**Pull request by Baconz2**
Tweaked a few lines of text so it makes more sense. Do what you want to do before merging.

Also, wouldn't Brazilian just be Portuguese? Wanted to ask before putting that in there.

### CODE REVIEW

**Comment by MatMoul** [comment]
Thanks for the PR, good work for the recommend...
But why changing pacstrap to download ?
The command run to install wget and libnewt is pacstrap and not wget or other.

**Comment by Baconz2** [comment]
Well, if you don't exactly know what pacstrap is, it wouldn't make sense, and I thought download would make sense in that case.

**Comment by MatMoul** [comment]
At this step you've already learned pacstrap when pacstraping base and kernel...
This is better with the used command.

**Comment by MatMoul** [comment]
@ line 1783 : `options+=("\sourceforge.net" " (Recommended)")`
Why the backslash before \sourceforge... ?

**Comment by Baconz2** [comment]
Hmm, don't remember writing that. Probably a typo, sorry

**Comment by MatMoul** [comment]
@Baconz2 Waiting your changes before mege it.... the \

**Comment by Baconz2** [comment]
Pushed the changes.

**Comment by MatMoul** [comment]
Thanks

**Pull request merged**
