### PR TITLE
Added Japanese translation

### PR DESCRIPTION
**Pull request by Hayao0819**
Added Japanese translation.
If the terminal emulator does not support Japanese characters, the characters will be garbled.

### CODE REVIEW

**Comment by MatMoul** [comment]
Thanks for the PR.
Translation seem good but it's doen't work because you need to set a japanase font (line 11).
You can test your PR with `sh archfi -t Hayao0819 master`

**Comment by Hayao0819** [comment]
Japanese is a multibyte character.
Therefore it cannot be used on the Linux console.
Only available in the terminal on some GUI.
Japanese font does not exist.

**Comment by MatMoul** [comment]
I've tried to investigate and you're right, it seem not possible for the console.
I leave your PR open...
One possibility is to detect if archfi is started on tty or a graphical console.
With this, it's possible to add Japanes when archfi is launched from GUI...

Not a priority for me but if you want to make a PR, you're free to do.

**Comment by pcoopergit** [comment]
> I've tried to investigate and you're right, it seem not possible for the console.
> I leave your PR open...
> One possibility is to detect if archfi is started on tty or a graphical console.
> With this, it's possible to add Japanes when archfi is launched from GUI...
> 
> Not a priority for me but if you want to make a PR, you're free to do.

Hi matmoul, fan of your work. Here's the workaround.
"en_US.UTF-8" and "ja_JP.UT8" both need to uncommented, & also "en_US.ISO-8859-1" and "ja_JP.EUC-JP".

Running "sudo locale-gen" then returned:
Generating locales...
  en_US.UTF-8... done
  en_US.ISO-8859-1... done
  ja_JP.EUC-JP... done
  ja_JP.UTF-8... done
Generation complete.

As expected. Oddly enough, the output of "locale" has not changed at all, but now japanese fonts show up correctly in shell and terminals, even without a reboot!

[Reference here](https://bbs.archlinux.org/viewtopic.php?id=197147)

**Pull request closed without merging**
