### PR TITLE
upload pt_PT file Portuguese(Portugal)

### PR DESCRIPTION
**Pull request by hugok79**
Create a file with the Portuguese(Portugual) translation.
The current Portuguese file should be renamed to Brazilian Portuguese
 This because Portuguese is (pt or pt_PT) and Brazilian Portuguese is (pt_BR)

### CODE REVIEW

**Comment by MatMoul** [comment]
Thanks for your PR, you're right for the pt_PT and pt_BR but I can't merge your PR as is because it doesn't work.
You need firstly rename the current portuguese to brazialian with "git mv" and then add your own portuguese file.
Then add brazilian on archfi menu (chooselanguage function at line 79) and preserve the name of the contributor for pt_BR
Then you can add portuguese with your own name.

Before sending your PR, don't miss to read https://github.com/MatMoul/archfi/blob/master/CONTRIBUTING.md and https://github.com/MatMoul/archfi/blob/master/lng/README.md for testing your changes

**Comment by hugok79** [comment]
Done

**Comment by MatMoul** [comment]
Thanks for the update, it's best...

Now I can test your translation with `archfi -t hugok79 master` in a WM...
But some chars are unreadables, you need to add `font=Lat2-Terminus16`

And archfi need to be updated...
Line 88 : replace MaxWilliamJF with your name
Line 81 : insert Barzilian with MaxWilliamJF as author

**Comment by MatMoul** [comment]
@hugok79 Sorry, I've just tested the current pt_BR and chars are unreadable too...
Lat2-Terminus16 seem not the good font :(

**Comment by hugok79** [comment]
Yes, I noticed that too... Characteres like ç pra ã are unreadable

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by hugok79** [comment]
@MatMoul "And archfi need to be updated...
Line 88 : replace MaxWilliamJF with your name
Line 81 : insert Barzilian with MaxWilliamJF as author"

Done

**Comment by hugok79** [comment]
What font do you suggest then?

**Comment by MatMoul** [comment]
@hugok79 Good work,
I can accept the PR as is but if you have an idea for the font, it would be even better...

**Comment by hugok79** [comment]
I translate the project [http://slint.fr/old/en/slint.html](url) [http://slint.fr/old/pt_PT/translators.html](url)
[http://slint.fr/wiki/en/start](url) created by French Didier Spaier and there all the Portuguese charachters are fine... 
I translate a lot of software and Linux Distros and other stuff but I'm not a programmer... 
I can ask Didier Spaier...

**Comment by MatMoul** [comment]
Don't have access to your link but consolefonts is stored in `/usr/share/kbd/consolefonts`

**Comment by MatMoul** [comment]
Found on a forum : https://www.slax.org/blog/19578-Console-font-and-keymappings.html
`lat0-16`

**Comment by MatMoul** [comment]
I confirm, `lat0-16` is good for pt_BR and certainly for pt_PT

**Comment by MatMoul** [comment]
@hugok79 Great, it's work for me...
You can add this font on pt_BR translation on an other PR...
Don't miss to work on the last src branch...

**Comment by MatMoul** [comment]
@hugok79 No need of a new PR for pt_BR, I've merged your last changes

**Pull request merged**
