### PR TITLE
Fix typo brazilian

### PR DESCRIPTION
**Pull request by hugok79**

### CODE REVIEW

**Comment by hugok79** [comment]
Change language in author to Brazilian Portuguese.

**Comment by MatMoul** [comment]
@hugok79 It would be nice to restart this PR from the last src commit because it was difficult to merge it now and don't miss to work on the src branch...
`git checkout src`

**Comment by MatMoul** [comment]
I've just pushed the last release and it seem that some PR was already include in past PR...
Then, no need to work more on these old PR...

**Comment by hugok79** [comment]
In short it's all done then.

**Pull request closed without merging**
