### PR TITLE
Create Arabic

### PR DESCRIPTION
**Pull request by mohdalawadi**
This is a translation of the Archfi script to Arabic.

### CODE REVIEW

**Comment by MatMoul** [comment]
Thanks for your PR but I can't use it...
Do you have tested it ?
You need to add arabic in https://github.com/MatMoul/archfi/blob/master/archfi at line 81...
and test it :
https://github.com/MatMoul/archfi/blob/master/lng/README.md

**Comment by mohdalawadi** [comment]
I proposed the change and added Arabic option on line 84.

Good enough?

**Comment by MatMoul** [comment]
Good start but the language menu is alpha sorted...
Letter A is the fisrt letter, this why Arabic need to be before Brazilian...
And it would be nice that you test the change to be sure that Arabic char are displayed in console.

**Comment by mohdalawadi** [comment]
Oh apologies.
And how can I test it now?

**Comment by MatMoul** [comment]
sh archfi -t {githubusername} {branchname}

sh archfi -t mohdalawadi master
or
sh archfi -t mohdalawadi patch-1

**Comment by mohdalawadi** [comment]
I cannot seem to see the Arabic option in the Language menu.

**Comment by MatMoul** [comment]
Sorry, after some test, the command work only with existant language...
I've edited manually archif before launch `sh archfi -t mohdalawadi patch-1`
And this is the result :
select lng
result
I pretty sure that you need to add a custom font but looking here :
https://wiki.archlinux.org/index.php/Fonts#Arabic
It seem that arabic fonts is all on aur...

**Comment by mohdalawadi** [comment]
How can we fix this?

**Comment by MatMoul** [comment]
it seem I found a correct font... `LatArCyrHeb-14`
Screenshot_20191229_152607
Just edit the line 12 and 13 to use the good locale and font...

**Pull request merged**
