### PR TITLE
BTRFS Fix

### PR DESCRIPTION
**Pull request by OliverSmeeton**
Fixes problems I had with installing to BTRFS root instead on sub vol

### CODE REVIEW

**Comment by MatMoul** [comment]
I have always used btrfs like this with success ...
Why do you want to add a nested subvolume named @ in the /root subvolume ?

**Comment by OliverSmeeton** [comment]
When I have used the script it has always installed to the btrfs root vol
(level 5) instead of a sub vol

**Comment by MatMoul** [comment]
Level 5 is a subvolume?

**Comment by OliverSmeeton** [comment]
From what I have heard it is advised not to install to the top level vol because some features like drive expansion do not work if installed to the root vol

**Comment by MatMoul** [comment]
What do you mean with toplevel?
Level 5 isn't ID 5.

**Comment by OliverSmeeton** [comment]
this is the layout when setup with the changes I suggested and from my understanding the top one (level 5) does not work with all the features of btrfs

**Comment by MatMoul** [comment]
Looking on the doc : https://btrfs.wiki.kernel.org/index.php/SysadminGuide
I don't find anything about limitation of subvolume, Level 5 or not.
I use the standard flat layout explained in the page.

Adding a subvolume @ in root for the root of the system has nosense...
Looking on OpenSuse, it has a @ subvolume at level5 and a root in it...

**Comment by OliverSmeeton** [comment]
OK thank you for your time and looking into It

**Pull request closed without merging**
